pipeline {
    agent { docker { image 'maven:3.9.12' } }

    stages {
         stage('Checkout') {
            steps {
                sh '''
                    rm -rf temp-clone
                    git clone https://github.com/sandeepparmar2k/devops-master-class.git temp-clone
                    cd temp-clone
                    ls -la
                '''
            }
        }
    
        stage ('Build') {
            steps {
                echo 'Building..'
                sh '''
                    docker --version
                    mvn clean install
                '''
            }
        }
        stage ('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
    }
}
