pipeline {
    agent { docker { image 'maven:3.9.12' } }

    stages {
        stage ('Build') {
            steps {
                echo 'Building..'
                sh 'docker --version'
                sh 'mvn --version'
            }
        }
        stage ('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
    }
}
